version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: velora_jobs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: velora_jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - velora_net

  backend:
    build: ./backend
    container_name: velora_jobs_backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db/velora_jobs
    depends_on:
      - db
    networks:
      - velora_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: velora_jobs_frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://jobs.ve-lora.my.id
    depends_on:
      - backend
    networks:
      - velora_net

networks:
  velora_net:
    driver: bridge

volumes:
  postgres_data:
